version: '3.2'
services:
  webserver:
    build: ./Docker/php
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
  mysql:
    build: ./Docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blogpirat
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: blogpirat
      MYSQL_USER: blogpirat
      MYSQL_PASSWORD: blogpirat
      MYSQL_HOST: localhost
    command: mysqld --sql_mode="" --character-set-server=utf8 --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --log-bin-trust-function-creators=1
    ports:
      - "3306:3306"
